# Generated by Django 4.0.4 on 2022-05-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_leaves_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='_from',
            new_name='fromdate',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='_to',
            new_name='todate',
        ),
    ]
